name: On push dev

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: npm run run:dev
        uses: cypress-io/github-action@v5 # use the explicit version number
